import XCTest

/// The macOS app must not start a BLE client just because it was built (260903).
///
/// This fork is an iPhone deployment. The macOS target exists to build and — more importantly — to
/// HOST `StrandTests`: its `TEST_HOST` / `BUNDLE_LOADER` point at `NOOP Staging.app` and the suite
/// links against that module via `@testable import Strand`, so the target cannot be removed without
/// taking every app-level test with it.
///
/// What CAN go is the behaviour: running that scheme launched a full BLE client on the development
/// Mac — a permission prompt, a scan, and connect attempts against a strap paired to the phone.
/// Radio traffic generated by the act of building.
///
/// Structural, like the recovery-fold and notification-wiring guards: the property is about which
/// code path a call sits on, so the test reads the source. A behavioural test cannot reach here —
/// `connectFromSystem` needs a live `CBCentralManager`, which is the very thing being avoided.
final class MacIdleAtLaunchTests: XCTestCase {

    private var bleManagerSource: String {
        get throws {
            let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
            return try String(contentsOf: root.appendingPathComponent("Strand/BLE/BLEManager.swift"),
                              encoding: .utf8)
        }
    }

    /// The gate exists, is macOS-only, and defaults to idle.
    func testTheMacOSGateIsOptInAndPlatformScoped() throws {
        let src = try bleManagerSource
        guard let fn = src.range(of: "func connectFromSystem(") else {
            return XCTFail("connectFromSystem not found — the gate's host method was renamed.")
        }
        // Look only at the method body, so an unrelated `#if os(macOS)` elsewhere cannot satisfy this.
        let body = String(src[fn.lowerBound...].prefix(1600))
        XCTAssertTrue(body.contains("#if os(macOS)"),
                      "the idle gate must be macOS-only — iOS auto-connect on radio-on IS the product")
        XCTAssertTrue(body.contains("macAutoConnectKey"),
                      "the gate must read the opt-in flag rather than hardcoding a decision")
        // `bool(forKey:)` returns false for an absent key: idle is the default, opt-in is deliberate.
        XCTAssertTrue(body.contains("guard UserDefaults.standard.bool(forKey:"),
                      "an absent flag must mean IDLE, so a fresh machine never scans on its own")
    }

    /// The gate must sit on the SYSTEM path only. A user pressing Connect is an explicit request and
    /// must still work — the macOS app stays usable, it just waits to be asked.
    func testTheUserInitiatedConnectIsNotGated() throws {
        let src = try bleManagerSource
        guard let userFn = src.range(of: "public func connect(model: WhoopModel = .persisted)"),
              let sysFn = src.range(of: "func connectFromSystem(model: WhoopModel = .persisted)") else {
            return XCTFail("Expected both the user-initiated and system-initiated connect entry points.")
        }
        // The user entry ends where the system one begins (it is declared immediately after).
        let userBody = String(src[userFn.lowerBound..<sysFn.lowerBound])
        XCTAssertFalse(userBody.contains("macAutoConnectKey"),
                       """
                       The user-initiated connect() is gated by the macOS idle flag. Pressing Connect \
                       would then do nothing on a Mac that has not opted in, which turns "idle until \
                       asked" into "broken". Gate only connectFromSystem().
                       """)
    }
}
