import XCTest

/// The macOS app must not start a BLE client just because it was built (260903).
///
/// This fork is an iPhone deployment. The macOS target exists to build and — more importantly — to
/// HOST `StrandTests`: its `TEST_HOST` / `BUNDLE_LOADER` point at `NOOP Staging.app` and the suite
/// links against that module via `@testable import Strand`, so the target cannot be removed without
/// taking every app-level test with it.
///
/// What CAN go is the behaviour: running that scheme launched a full BLE client on the development
/// Mac — a permission prompt, a scan, and connect attempts against a strap paired to the phone.
/// Radio traffic generated by the act of building.
///
/// Structural, like the recovery-fold and notification-wiring guards: the property is about which
/// code path a call sits on, so the test reads the source. A behavioural test cannot reach here —
/// `connectFromSystem` needs a live `CBCentralManager`, which is the very thing being avoided.
final class MacIdleAtLaunchTests: XCTestCase {

    private var bleManagerSource: String {
        get throws {
            let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
            return try String(contentsOf: root.appendingPathComponent("Strand/BLE/BLEManager.swift"),
                              encoding: .utf8)
        }
    }

    /// The gate exists, is macOS-only, and defaults to idle.
    func testTheMacOSGateIsOptInAndPlatformScoped() throws {
        let src = try bleManagerSource
        guard let fn = src.range(of: "func connectFromSystem(") else {
            return XCTFail("connectFromSystem not found — the gate's host method was renamed.")
        }
        // Look only at the method body, so an unrelated `#if os(macOS)` elsewhere cannot satisfy this.
        let body = String(src[fn.lowerBound...].prefix(1600))
        XCTAssertTrue(body.contains("#if os(macOS)"),
                      "the idle gate must be macOS-only — iOS auto-connect on radio-on IS the product")
        XCTAssertTrue(body.contains("macAutoConnectKey"),
                      "the gate must read the opt-in flag rather than hardcoding a decision")
        // `bool(forKey:)` returns false for an absent key: idle is the default, opt-in is deliberate.
        XCTAssertTrue(body.contains("guard UserDefaults.standard.bool(forKey:"),
                      "an absent flag must mean IDLE, so a fresh machine never scans on its own")
    }

    /// The gate must sit on the SYSTEM path only. A user pressing Connect is an explicit request and
    /// must still work — the macOS app stays usable, it just waits to be asked.
    func testTheUserInitiatedConnectIsNotGated() throws {
        let src = try bleManagerSource
        guard let userFn = src.range(of: "public func connect(model: WhoopModel = .persisted)"),
              let sysFn = src.range(of: "func connectFromSystem(model: WhoopModel = .persisted)") else {
            return XCTFail("Expected both the user-initiated and system-initiated connect entry points.")
        }
        // The user entry ends where the system one begins (it is declared immediately after).
        let userBody = String(src[userFn.lowerBound..<sysFn.lowerBound])
        XCTAssertFalse(userBody.contains("macAutoConnectKey"),
                       """
                       The user-initiated connect() is gated by the macOS idle flag. Pressing Connect \
                       would then do nothing on a Mac that has not opted in, which turns "idle until \
                       asked" into "broken". Gate only connectFromSystem().
                       """)
    }

    /// Building the recorder must not touch CoreLocation (260903).
    ///
    /// `AppModel` constructs `GpsWorkoutRecorder` eagerly at launch. A `CLLocationManager` held in a
    /// STORED property — and having its delegate assigned in `init` — registers the process with the
    /// location daemon right there, which surfaced as location requests every time the macOS app was
    /// run, with no workout started. Same shape as the BLE complaint above: a permission prompt
    /// caused by the act of building.
    ///
    /// The manager is therefore lazy, and `init` must stay empty of it. Structural for the same
    /// reason as the tests above: instantiating the recorder here to prove the negative would be
    /// the very thing under test.
    func testConstructingTheGpsRecorderDoesNotTouchCoreLocation() throws {
        let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
        let src = try String(contentsOf: root.appendingPathComponent("Strand/App/GpsWorkoutRecorder.swift"),
                             encoding: .utf8)
        XCTAssertTrue(src.contains("private lazy var manager: CLLocationManager"),
                      """
                      The CLLocationManager is a stored (non-lazy) property again, so it is built                       when the recorder is — at app launch — and registers with the location daemon                       before any workout exists.
                      """)
        guard let initRange = src.range(of: "override init() {"),
              let initEnd = src.range(of: "}", range: initRange.upperBound..<src.endIndex) else {
            return XCTFail("Expected an `override init()` in GpsWorkoutRecorder.")
        }
        let initBody = String(src[initRange.upperBound..<initEnd.lowerBound])
        XCTAssertFalse(initBody.contains("manager"),
                       """
                       `init` touches `manager`, which forces the lazy property immediately and                        defeats the deferral. Configure the manager inside its lazy initializer.
                       """)
    }
}

/// The macOS app must not INSTANTIATE a CoreBluetooth client just because it launched (260906).
///
/// The 260903 tests above pass, and the prompt still appeared. That is the lesson worth keeping: they
/// pinned the *gate on connecting*, and the macOS Bluetooth permission prompt does not come from
/// connecting — it comes from instantiating a `CBCentralManager`, which `init` did unconditionally.
/// The scan and the connect attempts genuinely stopped, which is why the fix looked complete; the
/// prompt, which was the reported symptom, did not.
///
/// So these assert the layer the earlier tests missed: on macOS the client is created LAZILY, on
/// first real use. Reading the source for the same reason the tests above do — constructing a
/// `BLEManager` in a test to observe the absence of a prompt is precisely the thing that would raise
/// one.
final class MacLazyCentralTests: XCTestCase {

    private func bleSource() throws -> String {
        let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
        return try String(contentsOf: root.appendingPathComponent("Strand/BLE/BLEManager.swift"),
                          encoding: .utf8)
    }

    /// No initializer may construct a central OUTSIDE an `#if os(iOS)` branch. Both initializers (the
    /// production one and the test/preview one) previously did, and the test-hosting initializer
    /// matters just as much: `StrandTests` runs inside the macOS app, so an eager client there raised
    /// the prompt on every test run as well as every build.
    func testNeitherInitializerConstructsACentralOnMacOS() throws {
        let src = try bleSource()
        // Three sites, and the COUNT is not the property — the platform scope is. Two initializers
        // (production and test/preview) each construct eagerly under `#if os(iOS)`, and the lazy
        // accessor has its own fallback. Asserting a count would fail the moment a fourth legitimate
        // site appeared while saying nothing about whether it was guarded; assert instead that every
        // eager site assigns `centralStorage` from inside an iOS branch, which is what keeps macOS
        // silent.
        let eager = src.components(separatedBy: "centralStorage = CBCentralManager(").count - 1
        XCTAssertEqual(eager, 2,
                       "both initializers should assign centralStorage eagerly (each inside its own "
                       + "`#if os(iOS)`); found \(eager)")
        for part in src.components(separatedBy: "centralStorage = CBCentralManager(").dropLast() {
            let preceding = String(part.suffix(400))
            XCTAssertTrue(preceding.contains("#if os(iOS)"),
                          "an eager construction outside `#if os(iOS)` puts the macOS prompt back: "
                          + preceding.suffix(160))
        }
        XCTAssertTrue(src.contains("CBCentralManagerOptionRestoreIdentifierKey"),
                      "iOS must keep its restorable client — background restoration depends on it")
        // The macOS arm of both initializers must be inert. If either still assigns, the prompt is back.
        XCTAssertFalse(src.contains("central = CBCentralManager("),
                       "a direct `central = CBCentralManager(...)` assignment is the regression: the "
                       + "client must be built through the lazy accessor, not in an initializer")
    }

    /// The storage is optional and the accessor materialises it. Without the optional there is nothing
    /// to defer.
    func testTheClientIsDeferredThroughOptionalStorage() throws {
        let src = try bleSource()
        XCTAssertTrue(src.contains("private var centralStorage: CBCentralManager?"),
                      "deferral needs optional storage")
        XCTAssertTrue(src.contains("private var central: CBCentralManager {"),
                      "and a computed accessor, so all 40 existing `central.` call sites are unchanged")
    }

    /// The permission-diagnostic path must not create a client merely by asking after its state.
    ///
    /// This one is easy to get wrong in the obvious direction: a status read looks harmless, but on a
    /// lazily-built client it is a construction — raising the very prompt this exists to avoid, from
    /// the code whose whole job is to REPORT on permission.
    func testTheUnauthorizedDiagnosticDoesNotCreateAClient() throws {
        let src = try bleSource()
        guard let fn = src.range(of: "func armUnauthorizedSettleDeadline()") else {
            return XCTFail("the unauthorized diagnostic has moved; this guard needs re-pointing")
        }
        let body = String(src[fn.upperBound...].prefix(900))
        XCTAssertTrue(body.contains("centralExists"),
                      "the diagnostic must check existence before reading state, or it constructs a "
                      + "client (and prompts) from a path that is only meant to observe: \(body.prefix(300))")
    }
}
